<html>
<head>
    <link href="/css/styles.css" rel="stylesheet" type="text/css">
</head>

<body>
<div class="form-style-2-heading">
    ${product.name}
    <br>
    <div class="form-style-2 .textarea-field">
        Price: &nbsp;${product.price}
    </div>
    <form method="post" class="form-style-2">
        <input class="form-style-2" type="submit" value="Buy"/>
    </form>
</div>
</body>
</html>