<html>
<head>
    <link href="/css/styles.css" rel="stylesheet" type="text/css">
</head>

<body>
<div class="form-style-2">
    <div class="form-style-2-heading">
        Please Sign Up!
    </div>
    <form method="post">
        <label for="firstName">Login
            <input class="input-field" type="text" id="login" name="login">
        </label>
        <label for="lastName">Password
            <input class="input-field" type="text" id="password" name="password">
        </label>
        <input type="submit" value="Sign Up">
    </form>
    <a href="/sign-in">Already signed up</a>
</div>
</body>
</html>